# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Using my background in robotics, computer vision, and machine learning, I am interested in uncovering the causal reasoning to develop
# artifically intelligent (AI) systems that can "think", "reason", and "imagine" for themselves. Such an intelligence should hold the key to solve the problems of Out-of-distribution (O.O.D.) generalization, 
# lifelong learning via abstraction, and the problem of handling catastrophic forgetting, prevelant in modern AI methods. 

# title: Mosam Dabhi
# name: Mosam Dabhi
# position: PhD Student
# email: mosam.dabhi@gmail.com
# description: >-
  
#   I am a Ph.D. candidate at the <a href="https://www.ri.cmu.edu/">Robotics Institute, Carnegie Mellon University</a>, advised by <a href="https://scholar.google.com/citations?user=vmAe35UAAAAJ&hl=en">Prof. Simon Lucey</a> and <a href="https://scholar.google.com/citations?user=Wdnc-mEAAAAJ&hl=en">Prof. Laszlo Jeni</a>. Previously, worked with <a href="https://shield.ai/company-executives/">Prof. Nathan Michael</a> on making drones operate intelligently.
#   <br><br>  
#   My research establishes the foundations of <b>Physical Intelligence</b>. I develop <b>Correspondence-Aware Architectures</b> that enable autonomous systems to reason about physical dynamics without relying on massive supervision.
#   <br><br>
#   Previously: Research Scientist Intern at <b>Apple (Vision Pro)</b> for 5 years.

title: Mosam Dabhi
name: Mosam Dabhi
position: Ph.D. Candidate
email: mosam.dabhi@gmail.com
description: >-
  I am a PhD candidate at the <a href="https://www.ri.cmu.edu/">Robotics Institute, Carnegie Mellon University</a>, advised by <a href="https://scholar.google.com/citations?user=vmAe35UAAAAJ&hl=en">Prof. Simon Lucey</a> and <a href="https://scholar.google.com/citations?user=Wdnc-mEAAAAJ&hl=en">Prof. Laszlo Jeni</a>. Prior to PhD, I worked with <a href="https://shield.ai/company-executives/">Prof. Nathan Michael</a> on intelligent drone autonomy.

  
  My research lays the foundations of <b>Physical Intelligence</b> via <b>correspondence-aware architectures</b> that enable autonomous systems to reason about real-world dynamics <b>without massive supervision</b>.

  
  Previously: Research Scientist Intern at <b>Apple (Vision Pro Team)</b> for 5 consecutive summers.

# My research establishes the foundations of Physical Intelligence, developing Architectures that enable autonomous systems to reason about physical dynamics without relying on massive supervision
# My research is on developing representations and architectures that enable autonomous systems to reason about physical dynamics without relying on massive supervision.
# <br><br>
# My research focuses on creating the perception backbone for robotics, bridging the gap between visual understanding and physical interaction.# <br><br>
# PhD student at the Robotics Institute, Carnegie Mellon University (CMU) with [Simon Lucey](https://scholar.google.com/citations?user=vmAe35UAAAAJ&hl=en) and [Laszlo Jeni](https://laszlojeni.com). Before that, I worked with [Nathan Michael](https://shield.ai/about-us/company-executives/nathan-michael/) at CMU on making drones operate intelligently.
  
# Purpose: Solving spatial intelligence merging existing data streams on internet with spatial signals (3D) to lead the base for intelligence that has physical reasoning.
# In my opinion: "AI could enable the creation of a versatile language through which all the existing scientific fields could be expressed."

# I am a Ph.D. student at the Robotics Institute, Carnegie Mellon University (CMU) where I investigate uncovering the representations that could be used as implicit priors and act as a placeholder for human visual intelligence.

# My goal is to understand how OOD reasoning (generalization) could be achieved to attain such general multi-modal intelligence in machines. To this end, I am currently focusing on extracting geometric reasoning via graph based representations to tackle this task.

# I am a PhD student at the Robotics Institute, Carnegie Mellon University (CMU) where I investigate causality within machine learning, and geometrical priors within computer vision.

# Previously, I finished my Masters at CMU with Simon Lucey.

# In my opinion: “AI could enable the creation of a versatile language through which all the existing scientific fields could be expressed.”


  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mosamdabhi.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mosamdabhi
github_username: mosamdabhi
linkedin_username: https://www.linkedin.com/in/mosam-dabhi-9395b09a/
google_scholar: b14VbHEAAAAJ
google_analytics: G-M3G9WN9KLK

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
